### ISSUE TITLE
Filter stream of pedestal ensembles to IO

### ISSUE THREAD

**Issue by mas12498** [mas12498/tracker#5]
Two parts:
1. EXPORT of the pedestals ensemble data that is generated by filter when processing target  trajectories:
     a. create in same .csv format per ensemble program ....
     b. by-pass both trajectory and pedestal observation re-computations
2. SENSOR_PLAYBACK capability Ability to import ensemble streams and directly feed filter

**Comment by caseyshields** [comment]
This requires a new file format that contains pedestal measurements.
As such it will be dependent on a specific set of pedestals.
To represent this the '.measurement' file's loader will take a pedestal ensemble as an argument.

I imagine the file format will be CSV with a header that looks something like;
```
time   S1_az   S1_el S1_rn   S2_az ...
```

The number of columns will depend on the number of sensors, their order and the flags for which readings are produced, as provided by the ensemble argument.

**Comment by caseyshields** [comment]
This is really close to the EnsembleTest…
I'm currently trying to tease out an ensemble object for easier code re-use.

I got the trjectory to write. Could you make sure it looks right and can produce it from you data?
Meanwhile I'll get the filter to run on an arbitrary stream of measurements...

**Comment by mas12498** [comment]
Looks pretty good to me. We discussed a bit lat night about the possibility of adding a 'validity boolean' per each of the sensors.
We could pack them into integers. For example, the ith bit (2^i) masks if the sensor is valid or not... so an 8-byte integer could mask up to 64 sensors.
What do you think?

**Comment by mas12498** [comment]
We could lead the file with a number of sensors and then post the validity bits in a long int...

**Comment by caseyshields** [comment]
I thought we were just assuming the measurement file was implicitly associated with some pedestal file because you need a pedestal file to create a measurement file?

Granted, this association is captured nowhere and is assumed the user is handling it; but even with the above modification the file wouldn't stands on it's own; the measurements are meaningless if we don't know where they are from.

If we want to got the route of having the measurement file be a stand-alone artifact we should probably print the pedestal file as the header of the measurements. Otherwise I would just associate them using a file naming convention.

**Comment by mas12498** [comment]
Good points. Leave off for now for reformat...
Can the written file be put thru 'play back'?

**Comment by caseyshields** [comment]
Just got it going I think. Can you take a look and try to run?

**Comment by mas12498** [comment]
Will do today between Aaron's verification exercises...

**Comment by mas12498** [comment]
Looks Great!
Wish I had something convenient to cast tracking.csv data to a trackpoints LLh file format and with time in integer milliseconds....

**Comment by caseyshields** [comment]
It could also use a way to specify Trajectories or Filter hints...
We'll put these in a new issue.
